name: capsule_toast
description: >-
  A reusable, brand-neutral Flutter package for morphing capsule notifications.
version: 1.1.0
homepage: https://github.com/FadyFayezYounan/capsule_toast
repository: https://github.com/FadyFayezYounan/capsule_toast

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - toast
  - notification
  - animation
  - ui
  - toastification

flutter:
